import type { LinkedInData, InstagramData, FacebookData, GoogleReviewsData, PlatformConfig, WeekEntry } from './types';

export const COLORS = {
  bg: '#DDEBF8',
  surface: '#FFFFFF',
  surfaceRaised: '#D3E6F6',
  border: '#AECBE6',
  borderSoft: '#C6DCEF',
  text: '#0C2038',
  textDim: '#3E6382',
  textFaint: '#6E8FAA',
  li: '#1558B8',
  liSoft: 'rgba(21,88,184,0.12)',
  ig: '#C22F6C',
  igSoft: 'rgba(194,47,108,0.12)',
  fb: '#5A45C9',
  fbSoft: 'rgba(90,69,201,0.12)',
  goog: '#EA4335',
  googSoft: 'rgba(234,67,53,0.12)',
  googYellow: '#FBBC05',
  googGreen: '#34A853',
  googBlue: '#4285F4',
  up: '#127F58',
  upSoft: 'rgba(18,127,88,0.12)',
  down: '#C23838',
  downSoft: 'rgba(194,56,56,0.12)',
  flat: '#A97714',
  flatSoft: 'rgba(169,119,20,0.14)',
};

export const PLATFORMS: Record<string, PlatformConfig> = {
  linkedin: {
    label: 'LinkedIn',
    accent: COLORS.li,
    soft: COLORS.liSoft,
    primaryKey: 'uniqueVisitors',
    primaryLabel: 'Unique Visitors',
    secondaryKey: 'pageViews',
    secondaryLabel: 'Page Views',
    metrics: [
      { key: 'impressions', label: 'Impressions' },
      { key: 'reactions', label: 'Reactions' },
      { key: 'comments', label: 'Comments' },
      { key: 'reposts', label: 'Reposts' },
      { key: 'pageViews', label: 'Page Views' },
      { key: 'uniqueVisitors', label: 'Unique Visitors' },
      { key: 'totalFollowers', label: 'Total Followers' },
      { key: 'newFollowers', label: 'New Followers' },
      { key: 'searchAppearances', label: 'Search Appearances' },
    ],
    groups: [
      {
        title: 'Content',
        fields: [
          { key: 'impressions', label: 'Impressions' },
          { key: 'reactions', label: 'Reactions' },
          { key: 'comments', label: 'Comments' },
          { key: 'reposts', label: 'Reposts' },
        ],
      },
      {
        title: 'Visitors',
        fields: [
          { key: 'pageViews', label: 'Page Views' },
          { key: 'uniqueVisitors', label: 'Unique Visitors' },
        ],
      },
      {
        title: 'Followers',
        fields: [
          { key: 'totalFollowers', label: 'Total Followers' },
          { key: 'newFollowers', label: 'New Followers' },
        ],
      },
      {
        title: 'Search Appearance',
        fields: [
          { key: 'searchAppearances', label: 'Search Appearances' },
        ],
      },
    ],
  },
  instagram: {
    label: 'Instagram',
    accent: COLORS.ig,
    soft: COLORS.igSoft,
    primaryKey: 'views',
    primaryLabel: 'Views',
    secondaryKey: 'reach',
    secondaryLabel: 'Reach',
    metrics: [
      { key: 'views', label: 'Views' },
      { key: 'reach', label: 'Reach' },
      { key: 'contentInteractions', label: 'Content Interactions' },
      { key: 'linkClicks', label: 'Link Clicks' },
      { key: 'visits', label: 'Visits' },
      { key: 'follows', label: 'Follows' },
    ],
  },
  facebook: {
    label: 'Facebook',
    accent: COLORS.fb,
    soft: COLORS.fbSoft,
    primaryKey: 'views',
    primaryLabel: 'Views',
    secondaryKey: 'viewers',
    secondaryLabel: 'Viewers',
    metrics: [
      { key: 'views', label: 'Views' },
      { key: 'viewers', label: 'Viewers' },
      { key: 'contentInteractions', label: 'Content Interactions' },
      { key: 'linkClicks', label: 'Link Clicks' },
      { key: 'visits', label: 'Visits' },
      { key: 'follows', label: 'Follows' },
    ],
  },
  google: {
    label: 'Google Reviews',
    accent: COLORS.goog,
    soft: COLORS.googSoft,
    primaryKey: 'totalReviews',
    primaryLabel: 'Total Reviews',
    secondaryKey: 'newReviews',
    secondaryLabel: 'New Reviews',
    metrics: [
      { key: 'averageRating', label: 'Average Rating (★)' },
      { key: 'totalReviews', label: 'Total Reviews' },
      { key: 'newReviews', label: 'New Reviews This Week' },
      { key: 'responseRate', label: 'Response Rate (%)' },
      { key: 'fiveStars', label: '5-Star Reviews' },
      { key: 'fourStars', label: '4-Star Reviews' },
      { key: 'threeStars', label: '3-Star Reviews' },
      { key: 'twoStars', label: '2-Star Reviews' },
      { key: 'oneStar', label: '1-Star Reviews' },
      { key: 'searchViews', label: 'Google Search Views' },
      { key: 'mapsViews', label: 'Google Maps Views' },
      { key: 'websiteClicks', label: 'Website Visits' },
      { key: 'directionRequests', label: 'Direction Requests' },
      { key: 'callClicks', label: 'Phone Call Clicks' },
    ],
    groups: [
      {
        title: 'Rating & Customer Trust',
        fields: [
          { key: 'averageRating', label: 'Average Rating (★)' },
          { key: 'totalReviews', label: 'Total Reviews' },
          { key: 'newReviews', label: 'New Reviews' },
          { key: 'responseRate', label: 'Response Rate (%)' },
        ],
      },
      {
        title: 'Star Breakdown',
        fields: [
          { key: 'fiveStars', label: '5-Star Reviews' },
          { key: 'fourStars', label: '4-Star Reviews' },
          { key: 'threeStars', label: '3-Star Reviews' },
          { key: 'twoStars', label: '2-Star Reviews' },
          { key: 'oneStar', label: '1-Star Reviews' },
        ],
      },
      {
        title: 'Discovery & Exposure',
        fields: [
          { key: 'searchViews', label: 'Search Views' },
          { key: 'mapsViews', label: 'Maps Views' },
        ],
      },
      {
        title: 'Customer Actions',
        fields: [
          { key: 'websiteClicks', label: 'Website Clicks' },
          { key: 'directionRequests', label: 'Direction Requests' },
          { key: 'callClicks', label: 'Phone Calls' },
        ],
      },
    ],
  },
};

export function emptyLinkedIn(): LinkedInData {
  return {
    impressions: 0,
    reactions: 0,
    comments: 0,
    reposts: 0,
    pageViews: 0,
    uniqueVisitors: 0,
    totalFollowers: 0,
    newFollowers: 0,
    searchAppearances: 0,
  };
}

export function emptyInstagram(): InstagramData {
  return {
    views: 0,
    reach: 0,
    contentInteractions: 0,
    linkClicks: 0,
    visits: 0,
    follows: 0,
  };
}

export function emptyFacebook(): FacebookData {
  return {
    views: 0,
    viewers: 0,
    contentInteractions: 0,
    linkClicks: 0,
    visits: 0,
    follows: 0,
  };
}

export function emptyGoogleReviews(): GoogleReviewsData {
  return {
    averageRating: 4.7,
    totalReviews: 10,
    newReviews: 1,
    responseRate: 100,
    fiveStars: 8,
    fourStars: 2,
    threeStars: 0,
    twoStars: 0,
    oneStar: 0,
    searchViews: 1240,
    mapsViews: 3120,
    websiteClicks: 156,
    directionRequests: 98,
    callClicks: 42,
    recentReviews: [
      { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
      { id: 'gr-2', author: 'Alok Rai', rating: 5, text: 'One of the best company where i visited,, ultimate services ☺️', time: '2025-02-08', relativeTime: 'a year ago' },
      { id: 'gr-3', author: 'Chetan Yadav', rating: 5, text: 'Genuinely best for consultation and construction', time: '2023-02-26', relativeTime: '3 years ago' },
      { id: 'gr-4', author: 'Chandra Sharma', rating: 5, text: 'Beautiful Palace', time: '2024-10-22', relativeTime: 'a year ago' },
      { id: 'gr-5', author: 'CHIKU BAIRWAL', rating: 4, text: 'Best in the town', time: '2023-10-31', relativeTime: '2 years ago' },
    ],
  };
}

export const SEED_WEEKS: WeekEntry[] = [
  {
    weekId: '2026-07-06',
    linkedin: {
      impressions: 420,
      reactions: 39,
      comments: 1,
      reposts: 0,
      pageViews: 17,
      uniqueVisitors: 8,
      totalFollowers: 49,
      newFollowers: 1,
      searchAppearances: 98,
    },
    instagram: {
      views: 237,
      reach: 46,
      contentInteractions: 15,
      linkClicks: 0,
      visits: 25,
      follows: 11,
    },
    facebook: {
      views: 78,
      viewers: 15,
      contentInteractions: 6,
      linkClicks: 0,
      visits: 17,
      follows: 8,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 840,
      mapsViews: 2150,
      websiteClicks: 112,
      directionRequests: 64,
      callClicks: 28,
      recentReviews: [
        { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
        { id: 'gr-2', author: 'Alok Rai', rating: 5, text: 'One of the best company where i visited,, ultimate services ☺️', time: '2025-02-08', relativeTime: 'a year ago' },
        { id: 'gr-3', author: 'Chetan Yadav', rating: 5, text: 'Genuinely best for consultation and construction', time: '2023-02-26', relativeTime: '3 years ago' },
      ],
    },
  },
  {
    weekId: '2026-07-13',
    linkedin: {
      impressions: 223,
      reactions: 18,
      comments: 0,
      reposts: 0,
      pageViews: 19,
      uniqueVisitors: 8,
      totalFollowers: 49,
      newFollowers: 3,
      searchAppearances: 78,
    },
    instagram: {
      views: 522,
      reach: 152,
      contentInteractions: 27,
      linkClicks: 0,
      visits: 16,
      follows: 13,
    },
    facebook: {
      views: 103,
      viewers: 71,
      contentInteractions: 6,
      linkClicks: 0,
      visits: 12,
      follows: 11,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 920,
      mapsViews: 2480,
      websiteClicks: 128,
      directionRequests: 79,
      callClicks: 32,
      recentReviews: [
        { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
        { id: 'gr-2', author: 'Alok Rai', rating: 5, text: 'One of the best company where i visited,, ultimate services ☺️', time: '2025-02-08', relativeTime: 'a year ago' },
      ],
    },
  },
  {
    weekId: '2026-07-20',
    linkedin: {
      impressions: 663,
      reactions: 69,
      comments: 0,
      reposts: 0,
      pageViews: 56,
      uniqueVisitors: 21,
      totalFollowers: 51,
      newFollowers: 3,
      searchAppearances: 98,
    },
    instagram: {
      views: 616,
      reach: 200,
      contentInteractions: 30,
      linkClicks: 0,
      visits: 54,
      follows: 4700,
    },
    facebook: {
      views: 122,
      viewers: 57,
      contentInteractions: 7,
      linkClicks: 0,
      visits: 13,
      follows: 40,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 1150,
      mapsViews: 3020,
      websiteClicks: 145,
      directionRequests: 92,
      callClicks: 39,
      recentReviews: [
        { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
        { id: 'gr-3', author: 'Chetan Yadav', rating: 5, text: 'Genuinely best for consultation and construction', time: '2023-02-26', relativeTime: '3 years ago' },
      ],
    },
  },
  {
    weekId: '2026-07-27',
    linkedin: {
      impressions: 780,
      reactions: 82,
      comments: 2,
      reposts: 1,
      pageViews: 68,
      uniqueVisitors: 26,
      totalFollowers: 56,
      newFollowers: 5,
      searchAppearances: 112,
    },
    instagram: {
      views: 745,
      reach: 240,
      contentInteractions: 38,
      linkClicks: 3,
      visits: 62,
      follows: 24,
    },
    facebook: {
      views: 145,
      viewers: 84,
      contentInteractions: 9,
      linkClicks: 2,
      visits: 19,
      follows: 15,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 1080,
      mapsViews: 2890,
      websiteClicks: 138,
      directionRequests: 84,
      callClicks: 35,
      recentReviews: [
        { id: 'gr-4', author: 'Chandra Sharma', rating: 5, text: 'Beautiful Palace', time: '2024-10-22', relativeTime: 'a year ago' },
      ],
    },
  },
  {
    weekId: '2026-08-03',
    linkedin: {
      impressions: 895,
      reactions: 95,
      comments: 4,
      reposts: 2,
      pageViews: 84,
      uniqueVisitors: 33,
      totalFollowers: 63,
      newFollowers: 7,
      searchAppearances: 128,
    },
    instagram: {
      views: 910,
      reach: 310,
      contentInteractions: 46,
      linkClicks: 5,
      visits: 78,
      follows: 31,
    },
    facebook: {
      views: 168,
      viewers: 96,
      contentInteractions: 12,
      linkClicks: 3,
      visits: 24,
      follows: 18,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 1240,
      mapsViews: 3120,
      websiteClicks: 156,
      directionRequests: 98,
      callClicks: 42,
      recentReviews: [
        { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
        { id: 'gr-2', author: 'Alok Rai', rating: 5, text: 'One of the best company where i visited,, ultimate services ☺️', time: '2025-02-08', relativeTime: 'a year ago' },
      ],
    },
  },
  {
    weekId: '2026-08-10',
    linkedin: {
      impressions: 1050,
      reactions: 112,
      comments: 5,
      reposts: 2,
      pageViews: 98,
      uniqueVisitors: 41,
      totalFollowers: 72,
      newFollowers: 9,
      searchAppearances: 145,
    },
    instagram: {
      views: 1120,
      reach: 380,
      contentInteractions: 58,
      linkClicks: 8,
      visits: 94,
      follows: 38,
    },
    facebook: {
      views: 195,
      viewers: 115,
      contentInteractions: 16,
      linkClicks: 5,
      visits: 31,
      follows: 22,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 1380,
      mapsViews: 3450,
      websiteClicks: 172,
      directionRequests: 108,
      callClicks: 48,
      recentReviews: [
        { id: 'gr-3', author: 'Chetan Yadav', rating: 5, text: 'Genuinely best for consultation and construction', time: '2023-02-26', relativeTime: '3 years ago' },
        { id: 'gr-5', author: 'CHIKU BAIRWAL', rating: 4, text: 'Best in the town', time: '2023-10-31', relativeTime: '2 years ago' },
      ],
    },
  },
  {
    weekId: '2026-08-17',
    linkedin: {
      impressions: 1240,
      reactions: 134,
      comments: 7,
      reposts: 3,
      pageViews: 115,
      uniqueVisitors: 52,
      totalFollowers: 84,
      newFollowers: 12,
      searchAppearances: 168,
    },
    instagram: {
      views: 1380,
      reach: 465,
      contentInteractions: 72,
      linkClicks: 12,
      visits: 118,
      follows: 46,
    },
    facebook: {
      views: 230,
      viewers: 138,
      contentInteractions: 21,
      linkClicks: 7,
      visits: 42,
      follows: 29,
    },
    google: {
      averageRating: 4.7,
      totalReviews: 10,
      newReviews: 1,
      responseRate: 100,
      fiveStars: 8,
      fourStars: 2,
      threeStars: 0,
      twoStars: 0,
      oneStar: 0,
      searchViews: 1520,
      mapsViews: 3780,
      websiteClicks: 194,
      directionRequests: 124,
      callClicks: 56,
      recentReviews: [
        { id: 'gr-1', author: 'Tilkesh Soni', rating: 5, text: 'Best experience ever!', time: '2026-07-06', relativeTime: '2 months ago' },
        { id: 'gr-2', author: 'Alok Rai', rating: 5, text: 'One of the best company where i visited,, ultimate services ☺️', time: '2025-02-08', relativeTime: 'a year ago' },
        { id: 'gr-3', author: 'Chetan Yadav', rating: 5, text: 'Genuinely best for consultation and construction', time: '2023-02-26', relativeTime: '3 years ago' },
        { id: 'gr-4', author: 'Chandra Sharma', rating: 5, text: 'Beautiful Palace', time: '2024-10-22', relativeTime: 'a year ago' },
        { id: 'gr-5', author: 'CHIKU BAIRWAL', rating: 4, text: 'Best in the town', time: '2023-10-31', relativeTime: '2 years ago' },
      ],
    },
  },
];
